name: CI_CD

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'  # Only trigger if YAML files change, including ingress
      - 'auth/**'
      - 'main/**'
      - 'domains/**'
      - 'store/**'
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - main
          - domain
          - store

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            hordansodevops/reseller_frontend_${{ matrix.service }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}/Dockerfile
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v3
        with:
          action: deploy
          strategy: basic
          imagepullsecrets: |
            ${{ secrets.REGISTRY_PULL_SECRET }}
          manifests: |
            k8s/${{ matrix.service }}-deployment.yaml
            k8s/${{ matrix.service }}-service.yaml
          images: |
            hordansodevops/reseller_frontend_${{ matrix.service }}:latest

#   deploy_ingress:
#     runs-on: ubuntu-latest
#     needs: build_and_deploy

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up kubectl
#         uses: azure/setup-kubectl@v4
#         with:
#           version: "v1.30.0"

#       - name: Kubernetes set context
#         uses: Azure/k8s-set-context@v3
#         with:
#           method: kubeconfig
#           kubeconfig: ${{ secrets.KUBECONFIG }}

#       - name: Deploy Ingress
#         uses: Azure/k8s-deploy@v3
#         with:
#           action: deploy
#           strategy: basic
#           manifests: |
#             k8s/ingress.yaml
